#!/usr/bin/env bash
set -e

apt update -y && apt install -y git tmux

cd /root
rm -rf northafrica.setup
git clone https://github.com/asloma1984/northafrica.setup.git

chmod +x /root/northafrica.setup/installer.sh
bash /root/northafrica.setup/installer.sh